export const data = [
    {
        id: 1,
        email: 'tcs@gmail.com',
        firstName: 'TCS ',
        lastName: 'admin',
        tenant: 'TCS',
        role: 'Editor',
    },
    {
        id: 2,
        email: 'wipro@gmail.com',
        firstName: 'wipro ',
        lastName: 'admin',
        tenant: 'wipro',
        role: 'Editor',
    },
    {
        id: 3,
        email: 'HCL@gmail.com',
        firstName: 'HCL ',
        lastName: 'admin',
        tenant: 'HCL',
        role: 'Editor',
    },
    {
        id: 4,
        email: 'zen@gmail.com',
        firstName: 'zen ',
        lastName: 'admin',
        tenant: 'zen',
        role: 'Editor',
    },
    {
        id: 5,
        email: 'xiomi@gmail.com',
        firstName: 'XIOMI ',
        lastName: 'admin',
        tenant: 'XIOMI',
        role: 'Editor',
    },
    {
        id: 6,
        email: 'redmi@gmail.com',
        firstName: 'redmi ',
        lastName: 'admin',
        tenant: 'redmi',
        role: 'Editor',
    },
    {
        id: 7,
        email: 'Accenture@gmail.com',
        firstName: 'Accenture ',
        lastName: 'admin',
        tenant: 'Accenture',
        role: 'Editor',
    },
    {
        id: 8,
        email: 'Coke@gmail.com',
        firstName: 'Coke ',
        lastName: 'admin',
        tenant: 'Coke',
        role: 'Editor',
    },
    {
        id: 9,
        email: 'Coke@gmail.com',
        firstName: 'Coke ',
        lastName: 'admin',
        tenant: 'Coke',
        role: 'Editor',
    },
    {
        id: 10,
        email: 'Coke@gmail.com',
        firstName: 'Coke ',
        lastName: 'admin',
        tenant: 'Coke',
        role: 'Editor',
    },
]